version: '3'

services:
  app-sistema-node:
    image: node:20
    user: node
    command: tail -f /dev/null
    container_name: app-sistema-node
    working_dir: /projeto/app-sistema-node
    depends_on:
      - app-sistema-db
    networks:
      - app-sistema-net
    env_file:
      - .env
    volumes:
      - ./:/projeto/app-sistema-node
    ports:
      - 3000:${PORT:-3000}

  app-sistema-db:
    image: postgres:16-alpine
    container_name: app-sistema-db
    env_file:
      - .db-postgres.env
    networks:
      - app-sistema-net
    ports:
      - 5432:5432
    volumes:
      - app-sistema-db-data:/var/lib/postgresql/data

networks:
  app-sistema-net:


volumes:
  app-sistema-db-data:


